#!/bin/bash -x
ant clean || exit 1
mkdir -p build/indexing-backend
ant "$@" build-zip && unzip -d build/indexing-backend dist/backend.zip && mv build/indexing-backend/backend build/indexing-backend/indexer || exit 1
mkdir -p build/indexing-backend/web
(cd web.main; ant clean && ant jar && cp -r dist/* ../build/indexing-backend/web) || exit 1

cp scripts/* build/indexing-backend

chmod u+x build/temp-indexing-backend/index
chmod u+x build/temp-indexing-backend/web

(cd build; zip -r indexing-backend.zip indexing-backend)
