#!/bin/bash -x
prepare_platform() {
if [ "$TRUNK_URL" == "" ] ; then
    TRUNK_URL="http://deadlock.netbeans.org/hudson/job/nbms-and-javadoc";
fi;

TRUNK_ID=`wget -q $TRUNK_URL/lastSuccessfulBuild/buildNumber -O -`

mkdir -p nbbuild

cd nbbuild
rm -rf netbeans
mkdir netbeans
mkdir -p download

rm `ls download/netbeans-hudson-trunk* | grep -v $TRUNK_ID`

cd netbeans

download_and_unpack_cluster() {
    if [ ! -e ../download/netbeans-hudson-trunk-$TRUNK_ID-$1.zip ] ; then
        wget -q -N $TRUNK_URL/$TRUNK_ID/artifact/nbbuild/dist/hudson-nbms-and-javadoc-$TRUNK_ID-$1.zip -O ../download/netbeans-hudson-trunk-$TRUNK_ID-$1.zip || exit
    fi;
    unzip -q ../download/*$TRUNK_ID-$1.zip || exit
}

for cluster in ide platform java harness nb apisupport extra enterprise cnd dlight websvccommon; do
    download_and_unpack_cluster $cluster;
done

cd ../..

PLATFORM=$PWD/nbbuild/netbeans
}

if [ "$PLATFORM" == "" ] ; then
    prepare_platform
fi;

ant -Dnbplatform.active.dir=$PLATFORM -f lib/download.xml download copy-from-platform

SUBPROJECTS="remoting language duplicates cmdline";

for subproject in $SUBPROJECTS; do
    (cd $subproject; ./build.sh -Dnbplatform.default.harness.dir=$PLATFORM/harness -Dnbplatform.default.netbeans.dest.dir=$PLATFORM -Dnbplatform.active.dir=$PLATFORM) || exit 1
done

mkdir -p build/updates

NBMS_SUBPROJECTS="remoting language duplicates";

cp `find $NBMS_SUBPROJECTS -type f -name "*.nbm"` build/updates
ant -Dnbplatform.default.harness.dir=$PLATFORM/harness -Dnbplatform.default.netbeans.dest.dir=$PLATFORM -Dnbplatform.active.dir=$PLATFORM -Ddist.base=$DIST_BASE build-auc || exit 1
gzip <build/updates/updates.xml >build/updates/updates.xml.gz

exit 0
