package org.netbeans.modules.jackpot30.impl.refactoring;

import java.awt.Component;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.EnumMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.netbeans.modules.jackpot30.impl.batch.BatchSearch.Scope;

/**
 *
 * @author lahvac
 */
public class FindDuplicatesRefactoringPanel extends javax.swing.JPanel {

    public FindDuplicatesRefactoringPanel(final ChangeListener parent, boolean allowVerify) {
        initComponents();
        pattern.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                parent.stateChanged(new ChangeEvent(FindDuplicatesRefactoringPanel.this));
            }
            public void removeUpdate(DocumentEvent e) {
                parent.stateChanged(new ChangeEvent(FindDuplicatesRefactoringPanel.this));
            }
            public void changedUpdate(DocumentEvent e) {}
        });
        ItemListener ilImpl = new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                parent.stateChanged(new ChangeEvent(FindDuplicatesRefactoringPanel.this));
            }
        };
        scope.addItemListener(ilImpl);
        verify.addItemListener(ilImpl);

        if (!allowVerify) {
            verify.setVisible(false);
        }
        
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();

        for (Scope s : Scope.values()) {
            dcbm.addElement(s);
        }
        
        scope.setModel(dcbm);
        scope.setRenderer(new RendererImpl());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pattern = new javax.swing.JTextPane();
        scope = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        verify = new javax.swing.JCheckBox();

        jScrollPane1.setViewportView(pattern);

        scope.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setLabelFor(pattern);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(FindDuplicatesRefactoringPanel.class, "FindDuplicatesRefactoringPanel.jLabel1.text")); // NOI18N

        jLabel2.setLabelFor(scope);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(FindDuplicatesRefactoringPanel.class, "FindDuplicatesRefactoringPanel.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(verify, org.openide.util.NbBundle.getMessage(FindDuplicatesRefactoringPanel.class, "FindDuplicatesRefactoringPanel.verify.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(verify)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(scope, 0, 388, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(jLabel2)
                .addContainerGap())
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scope, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(verify))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setPattern(String pattern) {
        this.pattern.setText(pattern);
    }

    public String getPattern() {
        return this.pattern.getText();
    }

    public void setScope(Scope scope) {
        this.scope.setSelectedItem(scope);
    }

    public Scope getScope() {
        return (Scope) this.scope.getSelectedItem();
    }

    public boolean getVerify() {
        return verify.isSelected();
    }

    public void setVerify(boolean verify) {
        this.verify.setSelected(verify);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane pattern;
    private javax.swing.JComboBox scope;
    private javax.swing.JCheckBox verify;
    // End of variables declaration//GEN-END:variables

    private static final class RendererImpl extends DefaultListCellRenderer {

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            String displayName;

            if (value instanceof Scope) {
                displayName = SCOPE_DISPLAY_NAMES.get((Scope) value);
            } else {
                displayName = value.toString();
            }
            
            return super.getListCellRendererComponent(list, displayName, index, isSelected, cellHasFocus);
        }

    }

    private static final Map<Scope, String> SCOPE_DISPLAY_NAMES;

    static {
        SCOPE_DISPLAY_NAMES = new EnumMap<Scope, String>(Scope.class);
        SCOPE_DISPLAY_NAMES.put(Scope.ALL_OPENED_PROJECTS, "All Opened Projects");
        SCOPE_DISPLAY_NAMES.put(Scope.ALL_REMOTE_PROJECTS, "All Remote Projects");
    }
    
}
